version: "3.9"
services:
  app-backend:
    build: ./backend
    container_name: 'backend'
    ports:
      - "8888:8888"
    depends_on:
      - redis
    environment:
      - .env

  app-frontend:
    build: ./frontend
    container_name: 'frontend'
    ports: 
        - 3000:3000

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379